### ISSUE TITLE
0x integration

### ISSUE THREAD

**Issue by benjyz** [economicnetwork/archon#37]
0x is a Ethereum-DEX protocol. archon has a generic broker architecture which can allow to trade against CEX or DEX at the same time. archon's role is to make it easier to use exchange wrappers and any exchange communication by adding middleware i.e. a "trading broker" described here [1]. the middleware makes it easy to write strategy code by bridging polling or streaming protocols, track orders and execution. 0x can be integrated by adding a exchange gateway to the broker

the calls needed are:

* get open orders
* get balance
* get orderbook
* submit order
* cancel order
* get transaction history

the broker will poll the smart contracts/relayers. the frontend of archon can be used to display the relevant data i.e. orderbooks, balances, orders, executions

relevant libraries that can be used is the python backend from makerdao
https://github.com/makerdao/pymaker
https://github.com/makerdao/pyexchange
https://github.com/0xProject/0x-monorepo/

[1] https://gist.github.com/benjyz/d9faef0926b20473716cf28286df77ed

**Comment by keo** [comment]
Please have 0x integration, we really need this.

Thank you.
